### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by wingsyuan** [rsennrich/wmt16-scripts#9]
Hi, 
@rsennrich

I try the script below, an error occur...
Is there any new version of script or solution?
~/stanford-corenlp-full-2014-10-31$ python stanford-conll-wrapper.py --corenlp stanford-corenlp-3.5.0.jar --corenlp-models stanford-corenlp-3.5.0-models.jar < 111 > output
number(1994-4, (-3)

Traceback (most recent call last):
  File "stanford-conll-wrapper.py", line 109, in <module>
    for sentence in get_sentences(codecs.getreader('UTF-8')(stanford)):
  File "stanford-conll-wrapper.py", line 61, in get_sentences
    rel, remainder = line.split('(')
ValueError: too many values to unpack (expected 2)

thanks a lot!
wingsyuan

**Comment by rsennrich** [comment]
can you please show the input text which generates this error? You seem to be using the correct version of corenlp (only 3.5.0 is supported), and I just double-checked that the script works on my machine.

**Comment by rsennrich** [comment]
closing this due to inactivity.
